import type { Metadata } from "next";
import { Open_Sans, Ubuntu_Sans } from "next/font/google";
import "./globals.css";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

const ubuntuSans = Ubuntu_Sans({
  variable: "--font-ubuntu-bold",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Jeffrey Scott Martin",
  description: "Generated by create next appCreative Engineer",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ubuntuSans.variable} ${openSans.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
